name: Publish package

on:
  push:
    tags:
      - 'eslint-config-react@v*.*.*'
      - 'prettier-config-react@v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: get-package
        run: |
          package=$(echo ${{github.ref_name}} | cut -d@ -f1)
          echo "package=$package" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@invoke-ai'

      - name: Install dependencies
        working-directory: 'packages/${{steps.get-package.outputs.package}}'
        run: pnpm install --frozen-lockfile

      - name: Publish
        shell: bash
        run: pnpm publish --access public --no-git-checks
        working-directory: 'packages/${{steps.get-package.outputs.package}}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
